[package]
name = "basic"
version = "0.1.0"
authors = ["Łukasz Biel <lukasz.p.biel@gmail.com>"]
edition = "2018"

[lib]
name = "async"
path = "src/lib.rs"
doctest = false

[dependencies]
test-case = { path = "../../" }
